# -*- coding: utf-8 -*-
"""CIND820 EDA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1elOf1d7416WZbFLkURtJK5KRls2HFXhq
"""

pip install pandas-profiling --upgrade

import pandas_profiling
import pandas as pd
from pandas_profiling import ProfileReport

df = pd.read_csv('Pasion et al dataset.csv', sep=',', header=0)
df.head()

report = ProfileReport(df)
report